  dev:
    image: nginx
    ports:
      - "443:443"
    #stdin_open: true
    #tty: true
    #entrypoint: /bin/bash
    #entrypoint: /entrypoint-cid.sh
    container_name: nginx
#    links:
#        - registry:registry
    volumes:
        - ./nginx/:/etc/nginx/conf.d
#  registry:
#    image: registry
#    ports:
#        - 5000:5000
#    environment:
#        REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry
#    volumes:
#        - ./registry:/registry
#    container_name: registry