version: "2"
services:
  dev:
    image: hibuz.com/dev:${TAG}
    build:
      context: ./dev
    ports:
      - "80:80"
      - "3000:3000"
    stdin_open: true
    tty: true
#    entrypoint: /bin/bash
    entrypoint: /entrypoint-cid.sh
    container_name: dev
