version: "2"
services:
  dev:
    image: hibuz.com/dev:1.0.15
    #build: ./dev
    #image: hdev
    ports:
      - 443:443
      - 80:80
    stdin_open: true
    tty: true
    #entrypoint: /entrypoint-cid.sh
    entrypoint: bash
    container_name: dev
    links:
        - registry:registry
    volumes:
        - ./nginx:/home/ubuntu/hpack/apps/nginx/conf
        #- ./data:/home/ubuntu/hpack/data2
  registry:
    image: registry
    ports:
        - 5000:5000
    environment:
        REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry
    volumes:
        - ./reg:/registry
    container_name: registry